### ISSUE TITLE
Missing MPI_Dist_graph_create_adjacent

### ISSUE THREAD

**Issue by sidarth-narayanan** [rookiehpc/rookiehpc.github.io#331] opened 2024-02-12 19:15 UTC
- Please check that this is not a duplicate of another existing issue then delete this message

**Comment by koaie** [comment] 2024-03-01 15:27
Duplicate of https://github.com/rookiehpc/rookiehpc.github.io/issues/323

**Closed as completed** 2024-03-01 19:10 UTC
Labels: duplicate
